### ISSUE TITLE
Cant download it on newer Android versions

### ISSUE THREAD

**Issue by Vejas04** [tamuseanmiller/Alpaca_Dashboard#15]
Hey, I have no clue how to run the project in Android Studio on a virtual machine and the download in the playstore doesnt work, because my android version higher ( I have a Samsung S9).
Any help on how I can fix it and how I can run the project on the IDE?

**Comment by tamuseanmiller** [comment]
Hi Vejas, this project lost support after Polygon removed access for Alpaca users. This will have to be have to be rewritten to support Alpaca's data API. That's why this was removed from the playstore.
